import { 
  collection, 
  doc, 
  getDoc, 
  getDocs, 
  setDoc, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  query, 
  where, 
  orderBy, 
  limit, 
  startAfter, 
  onSnapshot, 
  writeBatch,
  serverTimestamp,
  QueryConstraint
} from 'firebase/firestore';
import { db } from '../config';
import { OperationType, QueryOptions } from '../types';
import { handleFirestoreError } from '../utils/errorHandler';
import { getTenantCollectionPath } from '../../tenant';

/**
 * Garante que o caminho da coleção está isolado sob /empresas/{empresaId}/...
 * Exige estritamente empresaId.
 */
export function resolveTenantPath(path: string, empresaId: string): string {
  if (!empresaId || typeof empresaId !== 'string' || !empresaId.trim()) {
    throw new Error('empresaId é obrigatório para resolver o caminho do tenant.');
  }
  const cleanTenant = empresaId.trim();
  if (path.startsWith(`empresas/${cleanTenant}/`)) {
    return path;
  }
  if (path.startsWith('empresas/')) {
    throw new Error(`Caminho inválido ou divergente do empresaId informado: ${path}`);
  }
  return getTenantCollectionPath(cleanTenant, path);
}

/**
 * Fetch a single document from a collection, fully typed with tenant isolation
 */
export async function getDocument<T>(path: string, id: string, empresaId: string): Promise<T | null> {
  const targetPath = resolveTenantPath(path, empresaId);
  const fullPath = `${targetPath}/${id}`;
  try {
    const docRef = doc(db, targetPath, id);
    const snap = await getDoc(docRef);
    if (!snap.exists()) {
      return null;
    }
    return { id: snap.id, ...snap.data() } as T;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, fullPath);
    return null;
  }
}

/**
 * Creates/replaces a document with a specified ID in tenant scope.
 */
export async function createDocument<T>(path: string, id: string, data: any, empresaId: string): Promise<void> {
  const targetPath = resolveTenantPath(path, empresaId);
  const fullPath = `${targetPath}/${id}`;
  try {
    const docRef = doc(db, targetPath, id);
    const payload = {
      ...data,
      id,
      createdAt: data.createdAt || serverTimestamp(),
      updatedAt: serverTimestamp(),
    };
    await setDoc(docRef, payload);
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, fullPath);
  }
}

/**
 * Adds a document with an autogenerated ID in tenant scope
 */
export async function addDocument<T>(path: string, data: any, empresaId: string): Promise<string> {
  const targetPath = resolveTenantPath(path, empresaId);
  try {
    const colRef = collection(db, targetPath);
    const payload = {
      ...data,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };
    const docRef = await addDoc(colRef, payload);
    return docRef.id;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, targetPath);
    return '';
  }
}

/**
 * Updates an existing document symmetrically in tenant scope
 */
export async function updateExistingDocument<T>(path: string, id: string, data: any, empresaId: string): Promise<void> {
  const targetPath = resolveTenantPath(path, empresaId);
  const fullPath = `${targetPath}/${id}`;
  try {
    const docRef = doc(db, targetPath, id);
    const payload = {
      ...data,
      updatedAt: serverTimestamp(),
    };
    await updateDoc(docRef, payload);
  } catch (error) {
    handleFirestoreError(error, OperationType.UPDATE, fullPath);
  }
}

/**
 * Deletes a document in tenant scope
 */
export async function removeDocument(path: string, id: string, empresaId: string): Promise<void> {
  const targetPath = resolveTenantPath(path, empresaId);
  const fullPath = `${targetPath}/${id}`;
  try {
    const docRef = doc(db, targetPath, id);
    await deleteDoc(docRef);
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, fullPath);
  }
}

/**
 * Standard query builder helper to compose Firestore query objects
 */
function buildQuery(path: string, options: QueryOptions | undefined, empresaId: string) {
  const targetPath = resolveTenantPath(path, empresaId);
  const colRef = collection(db, targetPath);
  const constraints: QueryConstraint[] = [];

  if (options?.filters) {
    for (const filter of options.filters) {
      constraints.push(where(filter.field, filter.operator, filter.value));
    }
  }

  if (options?.orderByField) {
    constraints.push(orderBy(options.orderByField, options.orderDirection || 'asc'));
  }

  if (options?.startAfterDoc) {
    constraints.push(startAfter(options.startAfterDoc));
  }

  if (options?.limitCount) {
    constraints.push(limit(options.limitCount));
  }

  return query(colRef, ...constraints);
}

/**
 * Query documents on a collection with specified structured filters and sorting in tenant scope
 */
export async function queryDocuments<T>(path: string, options: QueryOptions | undefined, empresaId: string): Promise<T[]> {
  const targetPath = resolveTenantPath(path, empresaId);
  try {
    const q = buildQuery(targetPath, options, empresaId);
    const snap = await getDocs(q);
    return snap.docs.map(doc => ({ id: doc.id, ...doc.data() }) as T);
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, targetPath);
    return [];
  }
}

/**
 * Subscribe to realtime collection change notifications in tenant scope
 */
export function subscribeCollection<T>(
  path: string, 
  options: QueryOptions | undefined, 
  onUpdate: (data: T[]) => void,
  onError: ((error: any) => void) | undefined,
  empresaId: string
): () => void {
  const targetPath = resolveTenantPath(path, empresaId);
  try {
    const q = buildQuery(targetPath, options, empresaId);
    const unsubscribe = onSnapshot(q, (snap) => {
      const items = snap.docs.map(doc => ({ id: doc.id, ...doc.data() }) as T);
      onUpdate(items);
    }, (error) => {
      if (onError) {
        onError(error);
      } else {
        handleFirestoreError(error, OperationType.LIST, targetPath);
      }
    });
    return unsubscribe;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, targetPath);
    return () => {};
  }
}

/**
 * Batch write multiple updates at once on the client side in tenant scope
 */
export async function executeBatchWrite(operations: Array<{
  type: 'create' | 'update' | 'delete';
  path: string;
  id: string;
  data?: any;
}>, empresaId: string): Promise<void> {
  try {
    const batch = writeBatch(db);
    for (const op of operations) {
      const targetPath = resolveTenantPath(op.path, empresaId);
      const docRef = doc(db, targetPath, op.id);
      if (op.type === 'create') {
        const payload = {
          ...op.data,
          id: op.id,
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp()
        };
        batch.set(docRef, payload);
      } else if (op.type === 'update') {
        const payload = {
          ...op.data,
          updatedAt: serverTimestamp()
        };
        batch.update(docRef, payload);
      } else if (op.type === 'delete') {
        batch.delete(docRef);
      }
    }
    await batch.commit();
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, 'batch_operation');
  }
}
