import { 
  collection, 
  doc, 
  getDoc, 
  getDocs, 
  setDoc, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  query, 
  where, 
  orderBy, 
  limit, 
  startAfter, 
  onSnapshot, 
  writeBatch,
  serverTimestamp,
  DocumentData,
  QueryConstraint
} from 'firebase/firestore';
import { db } from '../config';
import { OperationType, QueryOptions } from '../types';
import { handleFirestoreError } from '../utils/errorHandler';

/**
 * Fetch a single document from a collection, fully typed
 */
export async function getDocument<T>(path: string, id: string): Promise<T | null> {
  const fullPath = `${path}/${id}`;
  try {
    const docRef = doc(db, path, id);
    const snap = await getDoc(docRef);
    if (!snap.exists()) {
      return null;
    }
    return { id: snap.id, ...snap.data() } as T;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, fullPath);
  }
}

/**
 * Creates/replaces a document with a specified ID. Enforces server timestamp and updatedAt metadata.
 */
export async function createDocument<T>(path: string, id: string, data: any): Promise<void> {
  const fullPath = `${path}/${id}`;
  try {
    const docRef = doc(db, path, id);
    const payload = {
      ...data,
      id,
      createdAt: data.createdAt || serverTimestamp(),
      updatedAt: serverTimestamp(),
    };
    await setDoc(docRef, payload);
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, fullPath);
  }
}

/**
 * Adds a document with an autogenerated ID
 */
export async function addDocument<T>(path: string, data: any): Promise<string> {
  try {
    const colRef = collection(db, path);
    const payload = {
      ...data,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };
    const docRef = await addDoc(colRef, payload);
    return docRef.id;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, path);
  }
}

/**
 * Updates an existing document symmetrically
 */
export async function updateExistingDocument<T>(path: string, id: string, data: any): Promise<void> {
  const fullPath = `${path}/${id}`;
  try {
    const docRef = doc(db, path, id);
    const payload = {
      ...data,
      updatedAt: serverTimestamp(),
    };
    await updateDoc(docRef, payload);
  } catch (error) {
    handleFirestoreError(error, OperationType.UPDATE, fullPath);
  }
}

/**
 * Deletes a document
 */
export async function removeDocument(path: string, id: string): Promise<void> {
  const fullPath = `${path}/${id}`;
  try {
    const docRef = doc(db, path, id);
    await deleteDoc(docRef);
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, fullPath);
  }
}

/**
 * Standard query builder helper to compose Firestore query objects
 */
function buildQuery(path: string, options?: QueryOptions) {
  const colRef = collection(db, path);
  const constraints: QueryConstraint[] = [];

  if (options?.filters) {
    for (const filter of options.filters) {
      constraints.push(where(filter.field, filter.operator, filter.value));
    }
  }

  if (options?.orderByField) {
    constraints.push(orderBy(options.orderByField, options.orderDirection || 'asc'));
  }

  if (options?.startAfterDoc) {
    constraints.push(startAfter(options.startAfterDoc));
  }

  if (options?.limitCount) {
    constraints.push(limit(options.limitCount));
  }

  return query(colRef, ...constraints);
}

/**
 * Query documents on a collection with specified structured filters and sorting
 */
export async function queryDocuments<T>(path: string, options?: QueryOptions): Promise<T[]> {
  try {
    const q = buildQuery(path, options);
    const snap = await getDocs(q);
    return snap.docs.map(doc => ({ id: doc.id, ...doc.data() }) as T);
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
  }
}

/**
 * Subscribe to realtime collection change notifications
 */
export function subscribeCollection<T>(
  path: string, 
  options: QueryOptions | undefined, 
  onUpdate: (data: T[]) => void,
  onError?: (error: any) => void
): () => void {
  try {
    const q = buildQuery(path, options);
    const unsubscribe = onSnapshot(q, (snap) => {
      const items = snap.docs.map(doc => ({ id: doc.id, ...doc.data() }) as T);
      onUpdate(items);
    }, (error) => {
      if (onError) {
        onError(error);
      } else {
        handleFirestoreError(error, OperationType.LIST, path);
      }
    });
    return unsubscribe;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
  }
}

/**
 * Batch write multiple updates at once on the client side
 */
export async function executeBatchWrite(operations: Array<{
  type: 'create' | 'update' | 'delete';
  path: string;
  id: string;
  data?: any;
}>): Promise<void> {
  try {
    const batch = writeBatch(db);
    for (const op of operations) {
      const docRef = doc(db, op.path, op.id);
      if (op.type === 'create') {
        const payload = {
          ...op.data,
          id: op.id,
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp()
        };
        batch.set(docRef, payload);
      } else if (op.type === 'update') {
        const payload = {
          ...op.data,
          updatedAt: serverTimestamp()
        };
        batch.update(docRef, payload);
      } else if (op.type === 'delete') {
        batch.delete(docRef);
      }
    }
    await batch.commit();
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, 'batch_operation');
  }
}
